spring:
  application:
    name: library-backend

  data:
    mongodb:
      uri: ur_mongodb_connection_string_here

server:
  port: 8080

jwt:
  secret: my-super-secret-key-change-this
  expiration: 86400000 # 24 hours

google:
  client-id: ur_google_client_id_here
  client-secret: ur_google_client_secret_here